DROP TABLE IF EXISTS products_sellers CASCADE;
DROP TABLE IF EXISTS product_entry_inbox CASCADE;
DROP TABLE IF EXISTS product_ingest_outbox CASCADE;
DROP TABLE IF EXISTS ingestion_history CASCADE;
DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE products (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku      TEXT NOT NULL UNIQUE,
    name     TEXT NOT NULL,
    brand    TEXT,
    category TEXT
);

CREATE TABLE products_sellers (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_name       TEXT NOT NULL,
    product_id        BIGINT NOT NULL REFERENCES products (id),
    seller_product_id TEXT NOT NULL,
    UNIQUE (seller_name, seller_product_id)
);

CREATE TABLE ingestion_history (
    id         TEXT PRIMARY KEY,
    file_name  TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE product_entry_inbox (
    correlation_id  TEXT PRIMARY KEY,
    idempotency_key TEXT NOT NULL,
    ingestion_id    TEXT NOT NULL,
    status          TEXT,
    reason          TEXT,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX ix_product_entry_inbox_idempotency_key ON product_entry_inbox (idempotency_key);

CREATE TABLE product_ingest_outbox (
    id             TEXT PRIMARY KEY,
    ingestion_id   TEXT NOT NULL UNIQUE REFERENCES ingestion_history (id),
    status         TEXT NOT NULL,
    attempts       INTEGER NOT NULL DEFAULT 0,
    failure_reason TEXT,
    created_at     TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ NOT NULL
);

CREATE INDEX ix_product_ingest_outbox_status_created ON product_ingest_outbox (status, created_at);
